# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - api-craftquestai-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.x'
  API_PROJECT: src/CraftQuest.Api/CraftQuest.Api.csproj
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build API
        run: dotnet build ${{ env.API_PROJECT }} -c Release

      - name: dotnet publish
        run: dotnet publish ${{ env.API_PROJECT }} -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B82C6330F29944FFAEE838340B972B47 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E67C82A7D3C347B09F32AF7CFD17F165 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ABF4F3F96980463CA4D91EE848DB10C2 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-craftquestai-prod'
          slot-name: 'Production'
          package: .
